version: '3'

services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - docker/postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db-data:
