name: caching packages dependencies

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 將存儲庫clone下來
      - name: Checkout code
        uses: actions/checkout@v3

      # https://github.com/actions/setup-python
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.13'
          cache: 'pipenv'
      - run: pipenv install
